package com.zencube.registry.notification.enums;

public enum NotificationEventType {
    USER_REGISTERED,
    EMAIL_VERIFIED,
    PASSWORD_RESET,
    ENTERPRISE_REGISTERED,
    ENTERPRISE_APPROVED,
    ENTERPRISE_REJECTED,
    ENTERPRISE_SUSPENDED,
    OPENING_CREATED,
    OPENING_APPROVED,
    OPENING_REJECTED,
    APPLICATION_SUBMITTED,
    APPLICATION_REVIEWED,
    APPLICATION_FORWARDED,
    INTERVIEW_SCHEDULED,
    APPLICATION_SELECTED,
    SUCCESS_STORY_CREATED,
    FORMAL_REQUEST_CREATED,
    INTERVIEW_REMINDER,
    CHAT_MESSAGE_RECEIVED
}

