package com.zencube.registry.notification.enums;

public enum NotificationType {
    APPLICATION_APPLIED,
    APPLICATION_REVIEWED,
    APPLICATION_FORWARDED,
    APPLICATION_SELECTED,
    APPLICATION_REJECTED,
    ENTERPRISE_APPROVED,
    ENTERPRISE_REJECTED,
    ENTERPRISE_SUSPENDED,
    ENTERPRISE_REACTIVATED,
    OPENING_APPROVED,
    PASSWORD_RESET,
    EMAIL_VERIFICATION,
    SUCCESS_STORY_CREATED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_COMPLETED,
    SYSTEM_ALERT,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    LOGIN_ALERT,
    INTEREST_FORMAL_REQUEST
}
